from .latent_export import (
    LatentExport,
    NODE_CLASS_MAPPINGS as LATENT_EXPORT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_EXPORT_DISPLAY_MAPPINGS
)
from .latent_import import (
    LatentImport,
    NODE_CLASS_MAPPINGS as LATENT_IMPORT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_IMPORT_DISPLAY_MAPPINGS
)
from .latent_loop import (
    LatentLoop,
    NODE_CLASS_MAPPINGS as LATENT_LOOP_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_LOOP_DISPLAY_MAPPINGS
)

NODE_CLASS_MAPPINGS = {
    **LATENT_EXPORT_MAPPINGS,
    **LATENT_IMPORT_MAPPINGS,
    **LATENT_LOOP_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LATENT_EXPORT_DISPLAY_MAPPINGS,
    **LATENT_IMPORT_DISPLAY_MAPPINGS,
    **LATENT_LOOP_DISPLAY_MAPPINGS,
}
